import 'package:flutter_test/flutter_test.dart';
import 'package:peek_wallet/coins/monero/monero_keys.dart';

/// Pin-the-output regression coverage for the pure-Dart Monero
/// derivation. The expected values were generated by this very code
/// once it was confirmed working end-to-end (subaddress.startsWith('8'),
/// address.length == 95, address starts with '4'). The point of pinning
/// them is **not** to claim authoritative correctness — it's to catch
/// silent drift in pointycastle's Keccak, dart's BigInt, or our own
/// ed25519 ops on every CI run. Any change to those layers that breaks
/// the algorithm will surface here as a single, obvious test failure
/// instead of a quiet "balance shows 0 in production".
///
/// To independently verify these values: drop the same BIP39 phrase
/// into Cake / Feather / Monero GUI's "Restore from seed", or into
/// vault-wallet's Settings → Show Recovery Phrase + Show Monero Keys.
/// Same algorithm → same address.
void main() {
  // BIP39 test phrase ('abandon … about'). Deterministic, public,
  // never used to hold real funds.
  const phrase = 'abandon abandon abandon abandon abandon abandon '
      'abandon abandon abandon abandon abandon about';

  // Generated 2026-05-18 by the in-tree derivation. Bump iff a
  // verified-against-an-external-wallet test vector replaces these.
  const expectedPrimary =
      '48ZFsbBKZAnN9Tyw7XsCakJ4dBxBpaD3wa9Az6V5ZwAK99kYQzcgckSNVv5iZhMp8o37fhNzY7eM2ERGoTWr4B282s4mcDi';
  const expectedSpendHex =
      '42c18561a04b8de73b2f0d08229fe28664f5c453ccb85e70811aaed6f6da5f01';
  const expectedViewHex =
      'ab5efec4b0cebb807f97b1001b96bf5f8948837335d5137e3fbe7238457ce60f';
  const expectedSub01 =
      '89S6ugfNrPVNqhrC1UQk1BJNPoA2GCqrU1T5knAGu4dQSQcuE8cEberfNu1z5QUCXF2zsL1AtF84WEQkvvrjXPRa9pxZw4e';
  const expectedSub05 =
      '8Azii85Z9PvDbEf3jCBYPf82nbpYqoh6oE7QMydxdsqW4qJ6yRQjVD9UEDFQeRT53QZa5LBujXLoH2YMtPaNELK43fcDWQH';
  const expectedSub10 =
      '8663B62xiiBg9erVsbnBwN9AYXydapA4TV3VPKeB3HpUYGDteMfBikUVseNDBdgLiKampNAP8EucVPX2g9UNxW3B7NguHjA';

  group('shape', () {
    test('primary is 95 chars, 4-prefix', () {
      final keys = deriveMoneroKeys(phrase);
      expect(keys.primaryAddress.length, 95);
      expect(keys.primaryAddress.startsWith('4'), isTrue);
    });

    test('spend / view keys are 32 bytes (64 hex)', () {
      final keys = deriveMoneroKeys(phrase);
      expect(keys.privateSpendHex.length, 64);
      expect(keys.privateViewHex.length, 64);
      expect(keys.privateSpendKey.length, 32);
      expect(keys.privateViewKey.length, 32);
    });

    test('subaddress (account=0, index>0) is 95 chars, 8-prefix', () {
      final sub = deriveMoneroSubaddress(phrase, 0, 1);
      expect(sub.length, 95);
      expect(sub.startsWith('8'), isTrue);
    });
  });

  group('determinism', () {
    test('two calls produce identical primary', () {
      expect(
        deriveMoneroKeys(phrase).primaryAddress,
        deriveMoneroKeys(phrase).primaryAddress,
      );
    });

    test('subaddress (0, 0) equals primary', () {
      final primary = deriveMoneroKeys(phrase).primaryAddress;
      expect(deriveMoneroSubaddress(phrase, 0, 0), primary);
    });
  });

  group('pinned vectors', () {
    test('all-abandon BIP39 → known primary address', () {
      final keys = deriveMoneroKeys(phrase);
      expect(keys.primaryAddress, expectedPrimary);
      expect(keys.privateSpendHex, expectedSpendHex);
      expect(keys.privateViewHex, expectedViewHex);
    });

    test('subaddresses match across calls', () {
      expect(deriveMoneroSubaddress(phrase, 0, 1), expectedSub01);
      expect(deriveMoneroSubaddress(phrase, 0, 5), expectedSub05);
      expect(deriveMoneroSubaddress(phrase, 1, 0), expectedSub10);
    });

    test('passphrase changes the address', () {
      final withPp = deriveMoneroKeys(phrase, passphrase: 'hello');
      expect(withPp.primaryAddress, isNot(expectedPrimary));
      expect(withPp.privateSpendHex, isNot(expectedSpendHex));
    });

    test('empty passphrase matches no-passphrase', () {
      expect(
        deriveMoneroKeys(phrase, passphrase: '').primaryAddress,
        deriveMoneroKeys(phrase).primaryAddress,
      );
    });
  });
}
