// Pure-Dart Monero address derivation.
//
// Port of vault-wallet/js/coins/monero.js — same algorithm so the
// addresses generated by both apps from the same BIP39 phrase are
// byte-identical. Verified by the round-trip test in
// test/monero_keys_test.dart.
//
// This file is intentionally pure Dart: no FFI, no native code. The
// monero_c FFI integration handles wallet sync + balance, but key
// derivation we do locally so we can show the receive address before
// the engine spins up.

import 'dart:typed_data';

import 'package:bip39/bip39.dart' as bip39;
import 'package:pointycastle/digests/keccak.dart';

/// Network bytes per Monero spec. Address(0x12), Integrated(0x13),
/// Subaddress(0x2A).
const int _addrPrefixMainnet = 0x12;
const int _addrPrefixSubaddress = 0x2A;

/// ed25519 field prime: 2^255 - 19.
final BigInt _p = (BigInt.one << 255) - BigInt.from(19);
/// ed25519 group order: 2^252 + 27742317777372353535851937790883648493.
final BigInt _l = (BigInt.one << 252) +
    BigInt.parse('27742317777372353535851937790883648493');

final BigInt _two = BigInt.two;
final BigInt _zero = BigInt.zero;
final BigInt _one = BigInt.one;

/// Modular reduction with positive remainder.
BigInt _fm(BigInt a, [BigInt? m]) {
  final mod = m ?? _p;
  final r = a % mod;
  return r.isNegative ? r + mod : r;
}

/// Modular exponentiation.
BigInt _fpow(BigInt b, BigInt e, [BigInt? m]) {
  final mod = m ?? _p;
  var r = _one;
  b = _fm(b, mod);
  while (e > _zero) {
    if (e.isOdd) r = r * b % mod;
    b = b * b % mod;
    e >>= 1;
  }
  return r;
}

/// Modular inverse via Fermat's little theorem (works since p is prime).
BigInt _finv(BigInt a) => _fpow(_fm(a), _p - _two);

/// ed25519 curve constant D = -121665/121666 mod p.
final BigInt _dC = _fm(BigInt.from(-121665) * _finv(BigInt.from(121666)));

/// A point in extended twisted Edwards coordinates (X, Y, Z, T).
typedef _Pt = List<BigInt>;
final _Pt _id4 = [_zero, _one, _one, _zero];

_Pt _pointAdd(_Pt p1, _Pt p2) {
  final x1 = p1[0], y1 = p1[1], z1 = p1[2], t1 = p1[3];
  final x2 = p2[0], y2 = p2[1], z2 = p2[2], t2 = p2[3];
  final a = _fm((y1 - x1) * (y2 - x2));
  final b = _fm((y1 + x1) * (y2 + x2));
  final c = _fm(_two * _dC * t1 * t2);
  final dv = _fm(_two * z1 * z2);
  final e = _fm(b - a);
  final f = _fm(dv - c);
  final g = _fm(dv + c);
  final h = _fm(b + a);
  return [_fm(e * f), _fm(g * h), _fm(f * g), _fm(e * h)];
}

_Pt _scalarMul(_Pt pt, BigInt s) {
  var r = List<BigInt>.from(_id4);
  var q = List<BigInt>.from(pt);
  while (s > _zero) {
    if (s.isOdd) r = _pointAdd(r, q);
    q = _pointAdd(q, q);
    s >>= 1;
  }
  return r;
}

Uint8List _compress(_Pt point) {
  final x = point[0], y = point[1], z = point[2];
  final zi = _finv(z);
  final ax = _fm(x * zi), ay = _fm(y * zi);
  final out = Uint8List(32);
  var v = ay;
  for (var i = 0; i < 32; i++) {
    out[i] = (v & BigInt.from(0xff)).toInt();
    v >>= 8;
  }
  if (ax.isOdd) out[31] |= 0x80;
  return out;
}

/// Standard ed25519 base point.
final _Pt _g = (() {
  final gy0 = _fm(BigInt.from(4) * _finv(BigInt.from(5)));
  final u = _fm(gy0 * gy0 - _one);
  final v = _fm(_dC * gy0 * gy0 + _one);
  final x2 = _fm(u * _finv(v));
  var x = _fpow(x2, (_p + BigInt.from(3)) ~/ BigInt.from(8));
  if (_fm(x * x) != x2) x = _fm(x * _fpow(_two, (_p - _one) ~/ BigInt.from(4)));
  if (x.isOdd) x = _p - x;
  return [x, gy0, _one, _fm(x * gy0)];
})();

/// Reduce 32 little-endian bytes mod the group order l.
BigInt _scReduce(Uint8List bytes) {
  var n = _zero;
  for (var i = bytes.length - 1; i >= 0; i--) {
    n = (n << 8) | BigInt.from(bytes[i]);
  }
  return _fm(n, _l);
}

Uint8List _scToBytes(BigInt s) {
  final out = Uint8List(32);
  var v = s;
  for (var i = 0; i < 32; i++) {
    out[i] = (v & BigInt.from(0xff)).toInt();
    v >>= 8;
  }
  return out;
}

Uint8List _keccak256(Uint8List data) {
  final d = KeccakDigest(256);
  d.update(data, 0, data.length);
  final out = Uint8List(32);
  d.doFinal(out, 0);
  return out;
}

/// Monero base58 encoding. Different from Bitcoin's — block-based.
const String _xmrB58 = '123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';
const List<int> _encSizes = [0, 2, 3, 5, 6, 7, 9, 10, 11];

String _xmrBase58(Uint8List data) {
  final full = data.length ~/ 8;
  final buf = StringBuffer();
  for (var i = 0; i < full; i++) {
    buf.write(_encBlock(data.sublist(i * 8, i * 8 + 8), 11));
  }
  final rem = data.length % 8;
  if (rem > 0) {
    buf.write(_encBlock(data.sublist(full * 8), _encSizes[rem]));
  }
  return buf.toString();
}

String _encBlock(Uint8List block, int size) {
  var n = _zero;
  for (final b in block) {
    n = (n << 8) | BigInt.from(b);
  }
  final out = List<String>.filled(size, '');
  for (var i = size - 1; i >= 0; i--) {
    out[i] = _xmrB58[(n % BigInt.from(58)).toInt()];
    n = n ~/ BigInt.from(58);
  }
  return out.join();
}

/// Encodes a varint per Monero / Bitcoin convention.
Uint8List _varint(int n) {
  final out = <int>[];
  var v = n;
  while (v >= 0x80) {
    out.add((v & 0x7f) | 0x80);
    v >>= 7;
  }
  out.add(v & 0x7f);
  return Uint8List.fromList(out);
}

/// The derived keypair + primary address for a Monero wallet. Cake-
/// compatible: same BIP39 seed → same address as vault-wallet and any
/// other wallet using this exact algorithm.
class MoneroKeys {
  const MoneroKeys({
    required this.privateSpendKey,
    required this.privateViewKey,
    required this.publicSpendKey,
    required this.publicViewKey,
    required this.primaryAddress,
  });

  final Uint8List privateSpendKey;
  final Uint8List privateViewKey;
  final Uint8List publicSpendKey;
  final Uint8List publicViewKey;
  final String primaryAddress;

  /// Hex string of the private spend key — what Cake / Feather /
  /// Monero GUI's "Restore from keys" expects.
  String get privateSpendHex => _toHex(privateSpendKey);
  String get privateViewHex => _toHex(privateViewKey);
}

/// Derive Monero keys + primary address from a BIP39 mnemonic.
///
/// Uses the same derivation as vault-wallet:
///   seed = PBKDF2-HMAC-SHA512(mnemonic, "mnemonic" + passphrase)
///   privSpend = sc_reduce(seed[0:32])
///   privView  = sc_reduce(keccak256(privSpend))
///   pubSpend  = privSpend × G
///   pubView   = privView  × G
///   addr      = base58(0x12 || pubSpend || pubView || keccak256(prefix)[0:4])
MoneroKeys deriveMoneroKeys(String mnemonic, {String passphrase = ''}) {
  final seed = bip39.mnemonicToSeed(mnemonic, passphrase: passphrase);
  final privSpend = _scReduce(Uint8List.sublistView(seed, 0, 32));
  final privSpendBytes = _scToBytes(privSpend);
  final privView = _scReduce(_keccak256(privSpendBytes));
  final privViewBytes = _scToBytes(privView);

  final pubSpend = _compress(_scalarMul(_g, privSpend));
  final pubView = _compress(_scalarMul(_g, privView));

  final raw = Uint8List(1 + 32 + 32)
    ..[0] = _addrPrefixMainnet
    ..setRange(1, 33, pubSpend)
    ..setRange(33, 65, pubView);
  final check = _keccak256(raw).sublist(0, 4);
  final full = Uint8List(raw.length + 4)
    ..setRange(0, raw.length, raw)
    ..setRange(raw.length, raw.length + 4, check);

  return MoneroKeys(
    privateSpendKey: privSpendBytes,
    privateViewKey: privViewBytes,
    publicSpendKey: pubSpend,
    publicViewKey: pubView,
    primaryAddress: _xmrBase58(full),
  );
}

/// Derive a Cake-compatible subaddress at (account, index). When both
/// are zero, returns the primary address (network byte 0x12);
/// otherwise the standard subaddress format (network byte 0x2A).
String deriveMoneroSubaddress(String mnemonic, int account, int index,
    {String passphrase = ''}) {
  if (account == 0 && index == 0) {
    return deriveMoneroKeys(mnemonic, passphrase: passphrase).primaryAddress;
  }

  final seed = bip39.mnemonicToSeed(mnemonic, passphrase: passphrase);
  final privSpend = _scReduce(Uint8List.sublistView(seed, 0, 32));
  final privView = _scReduce(_keccak256(_scToBytes(privSpend)));
  final aBytes = _scToBytes(privView);

  // m_i = sc_reduce(keccak256("SubAddr\0" || a || varint(M) || varint(N)))
  final tag = Uint8List.fromList('SubAddr '.codeUnits);
  final accVI = _varint(account);
  final idxVI = _varint(index);
  final buf = Uint8List(tag.length + 32 + accVI.length + idxVI.length);
  var off = 0;
  buf.setRange(off, off + tag.length, tag); off += tag.length;
  buf.setRange(off, off + 32, aBytes); off += 32;
  buf.setRange(off, off + accVI.length, accVI); off += accVI.length;
  buf.setRange(off, off + idxVI.length, idxVI);
  final m = _scReduce(_keccak256(buf));

  // D = b·G + m·G; C = a · D.
  final b = _scalarMul(_g, privSpend);
  final mG = _scalarMul(_g, m);
  final d = _pointAdd(b, mG);
  final c = _scalarMul(d, privView);

  final raw = Uint8List(1 + 32 + 32)
    ..[0] = _addrPrefixSubaddress
    ..setRange(1, 33, _compress(d))
    ..setRange(33, 65, _compress(c));
  final check = _keccak256(raw).sublist(0, 4);
  final full = Uint8List(raw.length + 4)
    ..setRange(0, raw.length, raw)
    ..setRange(raw.length, raw.length + 4, check);
  return _xmrBase58(full);
}

String _toHex(Uint8List bytes) {
  final buf = StringBuffer();
  for (final b in bytes) {
    buf.write(b.toRadixString(16).padLeft(2, '0'));
  }
  return buf.toString();
}
